//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSA_Assignment1_Sit1.ProductCommentServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductCommentServ.IProductComment")]
    public interface IProductComment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductComment/GetCommentsByProductID", ReplyAction="http://tempuri.org/IProductComment/GetCommentsByProductIDResponse")]
        Common.Comment[] GetCommentsByProductID(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCommentChannel : DSA_Assignment1_Sit1.ProductCommentServ.IProductComment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCommentClient : System.ServiceModel.ClientBase<DSA_Assignment1_Sit1.ProductCommentServ.IProductComment>, DSA_Assignment1_Sit1.ProductCommentServ.IProductComment {
        
        public ProductCommentClient() {
        }
        
        public ProductCommentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCommentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCommentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCommentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Comment[] GetCommentsByProductID(int id) {
            return base.Channel.GetCommentsByProductID(id);
        }
    }
}
