//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSA_Assignment1_Sit1.UserAccountServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAccountServ.IUserAccount")]
    public interface IUserAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/AddUser", ReplyAction="http://tempuri.org/IUserAccount/AddUserResponse")]
        void AddUser(Common.User user, int[] roles, Common.Account a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetUserByID", ReplyAction="http://tempuri.org/IUserAccount/GetUserByIDResponse")]
        Common.User GetUserByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetAccountByUsername", ReplyAction="http://tempuri.org/IUserAccount/GetAccountByUsernameResponse")]
        Common.Account GetAccountByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetUserByEmail", ReplyAction="http://tempuri.org/IUserAccount/GetUserByEmailResponse")]
        Common.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetAllTowns", ReplyAction="http://tempuri.org/IUserAccount/GetAllTownsResponse")]
        Common.Town[] GetAllTowns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetAllRoles", ReplyAction="http://tempuri.org/IUserAccount/GetAllRolesResponse")]
        Common.Role[] GetAllRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetAllAccounts", ReplyAction="http://tempuri.org/IUserAccount/GetAllAccountsResponse")]
        Common.Account[] GetAllAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccount/GetUserByAccountID", ReplyAction="http://tempuri.org/IUserAccount/GetUserByAccountIDResponse")]
        Common.User GetUserByAccountID(int aID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAccountChannel : DSA_Assignment1_Sit1.UserAccountServ.IUserAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAccountClient : System.ServiceModel.ClientBase<DSA_Assignment1_Sit1.UserAccountServ.IUserAccount>, DSA_Assignment1_Sit1.UserAccountServ.IUserAccount {
        
        public UserAccountClient() {
        }
        
        public UserAccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(Common.User user, int[] roles, Common.Account a) {
            base.Channel.AddUser(user, roles, a);
        }
        
        public Common.User GetUserByID(int id) {
            return base.Channel.GetUserByID(id);
        }
        
        public Common.Account GetAccountByUsername(string username) {
            return base.Channel.GetAccountByUsername(username);
        }
        
        public Common.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public Common.Town[] GetAllTowns() {
            return base.Channel.GetAllTowns();
        }
        
        public Common.Role[] GetAllRoles() {
            return base.Channel.GetAllRoles();
        }
        
        public Common.Account[] GetAllAccounts() {
            return base.Channel.GetAllAccounts();
        }
        
        public Common.User GetUserByAccountID(int aID) {
            return base.Channel.GetUserByAccountID(aID);
        }
    }
}
