//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSA_Assignment1_Sit1.OrderServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServ.IOrder")]
    public interface IOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrderStatusByID", ReplyAction="http://tempuri.org/IOrder/GetOrderStatusByIDResponse")]
        Common.OrderStatus GetOrderStatusByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrderStatusByName", ReplyAction="http://tempuri.org/IOrder/GetOrderStatusByNameResponse")]
        Common.OrderStatus GetOrderStatusByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrderByAccountAndStatus", ReplyAction="http://tempuri.org/IOrder/GetOrderByAccountAndStatusResponse")]
        Common.Order GetOrderByAccountAndStatus(int aid, int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetProductOrderByOrderIDAndProductID", ReplyAction="http://tempuri.org/IOrder/GetProductOrderByOrderIDAndProductIDResponse")]
        Common.ProductOrder GetProductOrderByOrderIDAndProductID(int oID, int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/UpdateProductOrder", ReplyAction="http://tempuri.org/IOrder/UpdateProductOrderResponse")]
        void UpdateProductOrder(Common.ProductOrder po);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/AddProductOrder", ReplyAction="http://tempuri.org/IOrder/AddProductOrderResponse")]
        void AddProductOrder(Common.ProductOrder po);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/AddOrder", ReplyAction="http://tempuri.org/IOrder/AddOrderResponse")]
        void AddOrder(Common.Order oder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrderByID", ReplyAction="http://tempuri.org/IOrder/GetOrderByIDResponse")]
        Common.Order GetOrderByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrdersByAccountID", ReplyAction="http://tempuri.org/IOrder/GetOrdersByAccountIDResponse")]
        Common.Order[] GetOrdersByAccountID(int aid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderChannel : DSA_Assignment1_Sit1.OrderServ.IOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderClient : System.ServiceModel.ClientBase<DSA_Assignment1_Sit1.OrderServ.IOrder>, DSA_Assignment1_Sit1.OrderServ.IOrder {
        
        public OrderClient() {
        }
        
        public OrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.OrderStatus GetOrderStatusByID(int id) {
            return base.Channel.GetOrderStatusByID(id);
        }
        
        public Common.OrderStatus GetOrderStatusByName(string name) {
            return base.Channel.GetOrderStatusByName(name);
        }
        
        public Common.Order GetOrderByAccountAndStatus(int aid, int sid) {
            return base.Channel.GetOrderByAccountAndStatus(aid, sid);
        }
        
        public Common.ProductOrder GetProductOrderByOrderIDAndProductID(int oID, int pID) {
            return base.Channel.GetProductOrderByOrderIDAndProductID(oID, pID);
        }
        
        public void UpdateProductOrder(Common.ProductOrder po) {
            base.Channel.UpdateProductOrder(po);
        }
        
        public void AddProductOrder(Common.ProductOrder po) {
            base.Channel.AddProductOrder(po);
        }
        
        public void AddOrder(Common.Order oder) {
            base.Channel.AddOrder(oder);
        }
        
        public Common.Order GetOrderByID(int id) {
            return base.Channel.GetOrderByID(id);
        }
        
        public Common.Order[] GetOrdersByAccountID(int aid) {
            return base.Channel.GetOrdersByAccountID(aid);
        }
    }
}
