//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSA_Assignment1_Sit1.ProductServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServ.IProduct")]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetAllProducts", ReplyAction="http://tempuri.org/IProduct/GetAllProductsResponse")]
        Common.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductByID", ReplyAction="http://tempuri.org/IProduct/GetProductByIDResponse")]
        Common.Product GetProductByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/getCategoryByName", ReplyAction="http://tempuri.org/IProduct/getCategoryByNameResponse")]
        Common.Category getCategoryByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductsByCategory", ReplyAction="http://tempuri.org/IProduct/GetProductsByCategoryResponse")]
        Common.Product[] GetProductsByCategory(int cID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductsByName", ReplyAction="http://tempuri.org/IProduct/GetProductsByNameResponse")]
        Common.Product[] GetProductsByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductsByPriceRange", ReplyAction="http://tempuri.org/IProduct/GetProductsByPriceRangeResponse")]
        Common.Product[] GetProductsByPriceRange(decimal priceFrom, decimal priceTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/sortByPriceAsc", ReplyAction="http://tempuri.org/IProduct/sortByPriceAscResponse")]
        Common.Product[] sortByPriceAsc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/sortByPriceDesc", ReplyAction="http://tempuri.org/IProduct/sortByPriceDescResponse")]
        Common.Product[] sortByPriceDesc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/sortByDateListed", ReplyAction="http://tempuri.org/IProduct/sortByDateListedResponse")]
        Common.Product[] sortByDateListed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/AddRating", ReplyAction="http://tempuri.org/IProduct/AddRatingResponse")]
        void AddRating(Common.Rating rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetRatingsByProduct", ReplyAction="http://tempuri.org/IProduct/GetRatingsByProductResponse")]
        double GetRatingsByProduct(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetRatingByAccountAndProduct", ReplyAction="http://tempuri.org/IProduct/GetRatingByAccountAndProductResponse")]
        Common.Rating GetRatingByAccountAndProduct(int aID, int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetHighlyRatedItem", ReplyAction="http://tempuri.org/IProduct/GetHighlyRatedItemResponse")]
        Common.Rating[] GetHighlyRatedItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetMostPurchasedItem", ReplyAction="http://tempuri.org/IProduct/GetMostPurchasedItemResponse")]
        Common.ProductOrder[] GetMostPurchasedItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductWithMostFaults", ReplyAction="http://tempuri.org/IProduct/GetProductWithMostFaultsResponse")]
        Common.Fault[] GetProductWithMostFaults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductWithLeastFaults", ReplyAction="http://tempuri.org/IProduct/GetProductWithLeastFaultsResponse")]
        Common.Fault[] GetProductWithLeastFaults();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : DSA_Assignment1_Sit1.ProductServ.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<DSA_Assignment1_Sit1.ProductServ.IProduct>, DSA_Assignment1_Sit1.ProductServ.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public Common.Product GetProductByID(int id) {
            return base.Channel.GetProductByID(id);
        }
        
        public Common.Category getCategoryByName(string name) {
            return base.Channel.getCategoryByName(name);
        }
        
        public Common.Product[] GetProductsByCategory(int cID) {
            return base.Channel.GetProductsByCategory(cID);
        }
        
        public Common.Product[] GetProductsByName(string name) {
            return base.Channel.GetProductsByName(name);
        }
        
        public Common.Product[] GetProductsByPriceRange(decimal priceFrom, decimal priceTo) {
            return base.Channel.GetProductsByPriceRange(priceFrom, priceTo);
        }
        
        public Common.Product[] sortByPriceAsc() {
            return base.Channel.sortByPriceAsc();
        }
        
        public Common.Product[] sortByPriceDesc() {
            return base.Channel.sortByPriceDesc();
        }
        
        public Common.Product[] sortByDateListed() {
            return base.Channel.sortByDateListed();
        }
        
        public void AddRating(Common.Rating rating) {
            base.Channel.AddRating(rating);
        }
        
        public double GetRatingsByProduct(int pID) {
            return base.Channel.GetRatingsByProduct(pID);
        }
        
        public Common.Rating GetRatingByAccountAndProduct(int aID, int pID) {
            return base.Channel.GetRatingByAccountAndProduct(aID, pID);
        }
        
        public Common.Rating[] GetHighlyRatedItem() {
            return base.Channel.GetHighlyRatedItem();
        }
        
        public Common.ProductOrder[] GetMostPurchasedItem() {
            return base.Channel.GetMostPurchasedItem();
        }
        
        public Common.Fault[] GetProductWithMostFaults() {
            return base.Channel.GetProductWithMostFaults();
        }
        
        public Common.Fault[] GetProductWithLeastFaults() {
            return base.Channel.GetProductWithLeastFaults();
        }
    }
}
